# fly.toml app configuration file generated for prettynice on 2024-03-30T21:39:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prettynice"
primary_region = "mia"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
